"""Generate the appendix gallery of example items: one vision-grounded + one text-grounded item per
D_M domain (DCI/VisText/SemArt/ROCO), plus one A-OKVQA (vision) and one RACE-high (text) from the
assembled pool. Copies/resizes each image into paper/figs/examples/ and writes a self-contained
paper/tables/appendix_examples.tex (LaTeX-escaped). Reproducible.

    python scripts/72_appendix_examples.py
"""
from __future__ import annotations

import ast
import json
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
DR = ROOT / "data"
FIGS = ROOT / "paper/figs/examples"; FIGS.mkdir(parents=True, exist_ok=True)
DOM_LABEL = {"dci": "DCI (natural photo)", "vistext": "VisText (statistical chart)",
             "semart": "SemArt (fine-art painting)", "roco": "ROCO (medical radiology)"}


def esc(s):
    s = (s or "").replace("\n", " ").strip()
    # curly quotes have no glyph in the template's ptmr8t font and vanish from the PDF
    for a, b in [("’", "'"), ("‘", "`"), ("“", "``"), ("”", "''")]:
        s = s.replace(a, b)
    for a, b in [("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"), ("$", r"\$"),
                 ("#", r"\#"), ("_", r"\_"), ("{", r"\{"), ("}", r"\}"), ("~", r"\textasciitilde{}"),
                 ("^", r"\textasciicircum{}")]:
        s = s.replace(a, b)
    return s


def truncate(s, n):
    w = (s or "").split()
    return " ".join(w[:n]) + (r" [\dots]" if len(w) > n else "")


def copy_img(src, tag):
    im = Image.open(src).convert("RGB")
    im.thumbnail((440, 440))
    out = FIGS / f"{tag}.jpg"; im.save(out, quality=85)
    return f"examples/{tag}.jpg"


LETTERS = "ABCD"
SEP = r"\\[3pt]\rule{\linewidth}{0.15pt}\\[3pt]"      # field separator inside the box


def block(tag, img_src, grounding, ctx_label, ctx_text, question, options, ci, note,
          hue="cyan"):
    """One example as a tcolorbox: header, thumbnail, and rule-separated fields.

    `hue` separates the two corpora at a glance: \dsname{} items are cyan, assembled-pool items
    are orange, since the two are built differently (oracle-generated vs retrieved) and a reader
    flipping through the appendix should not have to re-read the subsection heading to tell which
    is which."""
    rel = copy_img(img_src, tag)
    opts = " \\quad ".join(
        (r"\textbf{" + f"{LETTERS[i]}. " + esc(o) + "}") if i == ci else f"{LETTERS[i]}. " + esc(o)
        for i, o in enumerate(options))
    return (
        rf"\begin{{tcolorbox}}[colback={hue}!5,colframe={hue}!40,arc=1mm,boxrule=0.3pt,"
        r"width=\textwidth,top=3pt,bottom=3pt,left=5pt,right=5pt]" "\n"
        r"\textbf{" + grounding + r"}" "\n"
        r"\tcbline" "\n"
        r"\noindent\begin{minipage}[t]{0.30\linewidth}\centering\vspace{0pt}"
        r"\includegraphics[width=\linewidth,height=3.4cm,keepaspectratio]{" + rel + r"}"
        r"\end{minipage}\hfill" "\n"
        r"\begin{minipage}[t]{0.66\linewidth}\small\vspace{0pt}" "\n"
        r"\textbf{" + ctx_label + r".}~" + esc(ctx_text) + SEP + "\n"
        r"\textbf{Question.}~" + esc(question) + SEP + "\n"
        r"\textbf{Options.}~" + opts + "\n"
        r"\end{minipage}" "\n"
        r"\tcbline" "\n"
        r"{\small\emph{" + note + r"}}" "\n"
        r"\end{tcolorbox}" "\n")


def main():
    dm = []
    for sp in ("train", "val", "test"):
        dm += [json.loads(l) for l in (DR / f"dm/multidomain_v1/splits/{sp}.jsonl").read_text().splitlines() if l.strip()]
    out = [r"% auto-generated by scripts/72_appendix_examples.py"]

    for dom in ["dci", "vistext", "semart", "roco"]:
        out.append(r"\subsection{" + DOM_LABEL[dom] + r"}")
        for lab in ["vision", "text"]:
            cand = [r for r in dm if r.get("source") == dom and r["label"] == lab]
            r = min(cand, key=lambda r: len((r.get("caption_for_filter") or "")) + len(r["question"]))
            grounding = "Vision-grounded" if lab == "vision" else "Text-grounded"
            note = ("The answer is read from the image; the caption is answer-irrelevant."
                    if lab == "vision" else
                    "The answer is stated in the caption; the image is answer-irrelevant.")
            out.append(block(f"{dom}_{lab}", r["image_path"], grounding, "Caption",
                             r.get("caption_for_filter"), r["question"], r["options"],
                             int(r["correct_index"]), note))

    # --- MoGround-Human: hand-authored items whose captions are written to prime a wrong option ---
    hm = {json.loads(l)["candidate_id"]: json.loads(l) for l in
          (DR / "dm/human_moground/frozen_20260801.jsonl").read_text().splitlines() if l.strip()}
    HUMAN = ["semart_00272-view_stp_v", "vistext_7512_v", "dci_sa_1552414_v", "vistext_6174_t"]
    out.append(r"\subsection{\dsname-Human (hand-authored)}")
    for cid in HUMAN:
        r = hm[cid]
        opts = r["options"]
        if isinstance(opts, str):
            opts = ast.literal_eval(opts)
        vis = r["label"] == "vision"
        out.append(block(f"human_{cid}", r["image_path"],
                         "Vision-grounded" if vis else "Text-grounded", "Caption",
                         r["caption_for_filter"], r["question"], opts, int(r["correct_index"]),
                         "The answer is read from the image; the caption is answer-irrelevant."
                         if vis else
                         "The answer is stated in the caption; the image is answer-irrelevant."))

    asm = [json.loads(l) for l in (DR / "dm/merged_aokvqa_racehigh/dm_all.jsonl").read_text().splitlines() if l.strip()]
    out.append(r"\subsection{Assembled companion pool}")
    PICK = {"vision": "aokvqa_aokvqa_5ht6g4fNyooffRhmXHqYnt"}   # hand-picked showcase item
    for lab, tag, src_label, disp in [("vision", "aokvqa", "Caption (distractor)", "A-OKVQA"),
                                       ("text", "race", "Passage (grounding source, truncated)", "RACE-high")]:
        cand = [r for r in asm if r["label"] == lab]
        r = (next((x for x in cand if x["candidate_id"] == PICK.get(lab)), None)
             or min(cand, key=lambda r: len(r["question"])))
        if lab == "vision":
            grounding = f"{disp}: vision-grounded"
            note = "The answer is read from the image; the retrieved caption is a cross-modal distractor."
            ctx = r.get("caption_for_filter")
        else:
            grounding = f"{disp}: text-grounded"
            note = "The answer is in the passage; the retrieved image is a cross-modal distractor."
            ctx = truncate(r.get("caption_for_filter"), 45)
        out.append(block(f"assembled_{tag}", r["image_path"], grounding, src_label, ctx,
                         r["question"], r["options"], int(r["correct_index"]), note, hue="orange"))

    (ROOT / "paper/tables/appendix_examples.tex").write_text("\n".join(out) + "\n")
    print(f"-> paper/tables/appendix_examples.tex  ({len(list(FIGS.glob('*.jpg')))} images in {FIGS})")


if __name__ == "__main__":
    main()
